작업형 제 2유형은 정확한 정답이 없으며 예시 답안 코드로 해설함.

<br>

In [1]:
import pandas as pd
import numpy as np

In [2]:
X_train = pd.read_csv('../yemoonsaBigdata/datasets/Part2/stellar_X_train.csv')
y_train = pd.read_csv('../yemoonsaBigdata/datasets/Part2/stellar_y_train.csv')
X_test = pd.read_csv('../yemoonsaBigdata/datasets/Part2/stellar_X_test.csv')

In [3]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   alpha     70000 non-null  float64
 1   delta     70000 non-null  float64
 2   u         70000 non-null  float64
 3   g         70000 non-null  float64
 4   r         70000 non-null  float64
 5   i         70000 non-null  float64
 6   z         70000 non-null  float64
 7   redshift  70000 non-null  float64
 8   run_ID    70000 non-null  int64
 9   rerun_ID  70000 non-null  int64
 10  cam_col   70000 non-null  int64
 11  field_ID  70000 non-null  int64
 12  plate     70000 non-null  int64
dtypes: float64(8), int64(5)
memory usage: 6.9 MB

In [4]:
X_train.describe()

,alpha,delta,u,g,r,i,z,redshift,run_ID,rerun_ID,cam_col,field_ID,plate
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.0,70000.000000,70000.000000,70000.000000
mean,177.535809,24.107885,21.938806,20.486718,19.644011,19.082969,18.624590,0.575246,4478.649443,301.0,3.510500,186.045714,5127.852900
std,96.483093,19.665057,37.942814,37.925201,1.852053,1.755997,37.904705,0.729921,1965.326847,0.0,1.585203,148.661268,2947.452991
min,0.005528,-18.785328,-9999.000000,-9999.000000,9.822070,9.469903,-9999.000000,-0.009971,109.000000,301.0,1.000000,11.000000,266.000000
25%,127.385304,5.115922,20.349987,18.957325,18.136183,17.733732,17.463838,0.052602,3185.000000,301.0,2.000000,82.000000,2525.750000
50%,180.706865,23.579507,22.183860,21.095445,20.122805,19.399590,19.001010,0.422838,4188.000000,301.0,4.000000,146.000000,4978.000000
75%,233.942154,39.871336,23.684145,22.121073,21.039012,20.391340,19.917578,0.700399,5326.000000,301.0,5.000000,241.000000,7389.000000
max,359.999615,82.947622,32.781390,31.602240,29.571860,32.141470,28.790550,7.011245,8162.000000,301.0,6.000000,989.000000,12547.000000

In [5]:
'''

이상치 제거

'''

train_dataset = pd.concat([X_train, y_train], axis=1)
train_dataset = train_dataset[train_dataset['u'] != -9999]

In [6]:
train_dataset.reset_index(drop=True, inplace=True)

In [7]:
train_dataset.describe()

,alpha,delta,u,g,r,i,z,redshift,run_ID,rerun_ID,cam_col,field_ID,plate,galaxy
count,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.0,69999.000000,69999.000000,69999.000000,69999.000000
mean,177.535145,24.108238,22.081964,20.629856,19.644032,19.082984,18.767701,0.575254,4478.702681,301.0,3.510522,186.040701,5127.878813,0.593808
std,96.483622,19.664976,2.248554,2.033576,1.852057,1.756005,1.764734,0.729923,1965.290408,0.0,1.585204,148.656411,2947.466071,0.491125
min,0.005528,-18.785328,10.996230,10.498200,9.822070,9.469903,9.612333,-0.009971,109.000000,301.0,1.000000,11.000000,266.000000,0.000000
25%,127.384192,5.117238,20.350000,18.957435,18.136075,17.733685,17.463885,0.052608,3185.000000,301.0,2.000000,82.000000,2525.500000,0.000000
50%,180.705886,23.580630,22.183900,21.095450,20.122810,19.399590,19.001020,0.422848,4188.000000,301.0,4.000000,146.000000,4978.000000,1.000000
75%,233.942330,39.872079,23.684160,22.121075,21.039035,20.391350,19.917595,0.700399,5326.000000,301.0,5.000000,241.000000,7389.000000,1.000000
max,359.999615,82.947622,32.781390,31.602240,29.571860,32.141470,28.790550,7.011245,8162.000000,301.0,6.000000,989.000000,12547.000000,1.000000

In [8]:
X_train = pd.DataFrame(train_dataset.iloc[:, :-1])
y_train = pd.DataFrame(train_dataset.iloc[:, -1])

In [9]:
# redshift가 이상함
X_train['redshift'].quantile([q/100 for q in range(90, 101)])

0.90    1.566266
0.91    1.675948
0.92    1.786824
0.93    1.910857
0.94    2.041589
0.95    2.186017
0.96    2.323494
0.97    2.485796
0.98    2.713839
0.99    3.116165
1.00    7.011245
Name: redshift, dtype: float64

약 2%만이 3을 넘는다는 것을 확인할 수 있다...

<br>

In [10]:
# 파생 변수 추가

X_train['redshift_upper_3'] = np.where(X_train['redshift'] > 3, 1, 0)
X_test['redshift_upper_3'] = np.where(X_test['redshift'] > 3, 1, 0)

In [11]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69999 entries, 0 to 69998
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   alpha             69999 non-null  float64
 1   delta             69999 non-null  float64
 2   u                 69999 non-null  float64
 3   g                 69999 non-null  float64
 4   r                 69999 non-null  float64
 5   i                 69999 non-null  float64
 6   z                 69999 non-null  float64
 7   redshift          69999 non-null  float64
 8   run_ID            69999 non-null  int64
 9   rerun_ID          69999 non-null  int64
 10  cam_col           69999 non-null  int64
 11  field_ID          69999 non-null  int64
 12  plate             69999 non-null  int64
 13  redshift_upper_3  69999 non-null  int64
dtypes: float64(8), int64(6)
memory usage: 7.5 MB

In [12]:
columns_remove = []
columns_num = ['alpha', 'delta', 'u', 'g', 'r', 'i', 'z', 'redshift']
columns_cat = ['run_ID', 'rerun_ID', 'cam_col', 'field_ID', 'plate', 'redshift_upper_3']
columns_y = ['galaxy']

In [13]:
X_train[columns_cat] = X_train[columns_cat].astype(str)
X_test[columns_cat] = X_test[columns_cat].astype(str)

In [14]:
train_dataset = pd.concat([X_train, y_train], axis=1)

for col in columns_num:
    print("-" * 80)
    print(col)
    print(train_dataset.groupby(columns_y)[col].describe(), end='\n\n')

--------------------------------------------------------------------------------
alpha
          count        mean        std       min         25%         50%
galaxy
0       28433.0  177.234737  99.202036  0.010959  120.997187  180.253146  \
1       41566.0  177.740638  94.579769  0.005528  131.392267  181.032298

               75%         max
galaxy
0       239.025694  359.999615
1       231.397544  359.989386

--------------------------------------------------------------------------------
delta
          count       mean        std        min       25%        50%
galaxy
0       28433.0  25.067356  20.141007 -18.785328  5.060842  26.372836  \
1       41566.0  23.452158  19.305416 -12.364701  5.136824  22.255904

              75%        max
galaxy
0       41.762988  82.947622
1       37.855667  77.615588

--------------------------------------------------------------------------------
u
          count      mean       std       min        25%        50%
galaxy
0       28433.0  21.34313  2.010059  10.99623  19.987270  21.355940  \
1       41566.0  22.58736  2.263188  13.89799  20.786442  22.847385

              75%       max
galaxy
0       22.548860  32.78139
1       24.207522  29.32565

--------------------------------------------------------------------------------
g
          count       mean       std       min       25%        50%
galaxy
0       28433.0  20.231791  1.851996  10.49820  19.00707  20.579190  \
1       41566.0  20.902150  2.106089  12.68849  18.90630  21.581005

              75%       max
galaxy
0       21.533270  30.60700
1       22.439442  31.60224

--------------------------------------------------------------------------------
r
          count       mean       std       min        25%       50%
galaxy
0       28433.0  19.734722  1.818405   9.82207  18.541890  20.15357  \
1       41566.0  19.581995  1.872222  11.77229  17.812303  20.10107

              75%       max
galaxy
0       21.125780  29.37411
1       20.963275  29.57186

--------------------------------------------------------------------------------
i
          count       mean       std        min        25%        50%
galaxy
0       28433.0  19.429044  1.795189   9.469903  18.254250  19.831600  \
1       41566.0  18.846264  1.688337  11.319370  17.377382  19.217675

              75%       max
galaxy
0       20.825140  32.14147
1       19.934773  30.16359

--------------------------------------------------------------------------------
z
          count       mean       std        min       25%       50%
galaxy
0       28433.0  19.240711  1.811976   9.612333  18.03419  19.61244  \
1       41566.0  18.444141  1.655606  10.897380  17.09492  18.76067

              75%       max
galaxy
0       20.627150  28.79055
1       19.463442  28.23829

--------------------------------------------------------------------------------
redshift
          count      mean       std       min       25%       50%       75%
galaxy
0       28433.0  0.801073  1.060163 -0.004136 -0.000095  0.000388  1.540357  \
1       41566.0  0.420785  0.263971 -0.009971  0.164568  0.456604  0.593396

             max
galaxy
0       7.011245
1       1.995524

수치형 중 의미있는 변수로 보이는 것은 `redshift`이다.

<br><br>

In [15]:
for col in columns_cat:
    print(train_dataset.groupby(col)[columns_y].mean().sort_values(by=columns_y, ascending=False), end='\n\n')

        galaxy
run_ID
2883       1.0
6121       1.0
8054       1.0
1897       1.0
4800       1.0
...        ...
5378       0.0
5237       0.0
5115       0.0
5060       0.0
994        0.0

[425 rows x 1 columns]

            galaxy
rerun_ID
301       0.593808

           galaxy
cam_col
1        0.619151
4        0.612120
5        0.610490
3        0.593031
2        0.583152
6        0.530405

          galaxy
field_ID
717          1.0
788          1.0
708          1.0
746          1.0
748          1.0
...          ...
934          0.0
933          0.0
932          0.0
931          0.0
940          0.0

[847 rows x 1 columns]

       galaxy
plate
999       1.0
6417      1.0
6388      1.0
6389      1.0
1900      1.0
...       ...
2560      0.0
2563      0.0
2564      0.0
5343      0.0
1891      0.0

[6187 rows x 1 columns]

                    galaxy
redshift_upper_3
0                 0.601125
1                 0.000000

범주형 중 의미있어 보이는 변수는 `cam_col`, `redshift_upper_3`이다.

<br>

In [16]:
# 범주형 데이터는 Label Encoder나 OneHot Encoder로 encoding해야 한다.

from sklearn.preprocessing import LabelEncoder


X = pd.concat([X_train, X_test])

for col in columns_cat:
    label_encoder = LabelEncoder()
    label_encoder.fit(X[col])
    
    X_train[col] = label_encoder.transform(X_train[col])
    X_test[col] = label_encoder.transform(X_test[col])

In [17]:
# 학습 데이터와 검증 데이터로 분리

from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.3, stratify=y_train)

In [18]:
# 수치형 데이터에 대해 Scaling 진행

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_tr[columns_num])

X_tr[columns_num] = scaler.transform(X_tr[columns_num])
X_val[columns_num] = scaler.transform(X_val[columns_num])
X_test[columns_num] = scaler.transform(X_test[columns_num])

In [19]:
# 학습 진행 (RandomForestClassifier)

from sklearn.ensemble import RandomForestClassifier

model_RF = RandomForestClassifier()
model_RF.fit(X_tr, y_tr.values.squeeze())

RandomForestClassifier()

In [20]:
# 학습 진행 (XGBClassifier)

from xgboost import XGBClassifier

model_XGB = XGBClassifier()
model_XGB.fit(X_tr, y_tr.values.squeeze())

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [21]:
# 평가

from sklearn.metrics import roc_auc_score

y_val_pred_RF = model_RF.predict_proba(X_val)
y_val_pred_XGB = model_XGB.predict_proba(X_val)

score_RF = roc_auc_score(y_val, y_val_pred_RF[:, 1])
score_XGB = roc_auc_score(y_val, y_val_pred_XGB[:, 1])

print(score_RF)
print(score_XGB)

0.9937745924333288
0.9939854713445915

In [22]:
len(X_train.columns)

14

In [23]:
model_RF.feature_importances_

array([0.01647308, 0.01554814, 0.06959264, 0.08733732, 0.04408588,
       0.07671454, 0.10729704, 0.50814607, 0.01091678, 0.        ,
       0.004124  , 0.00846002, 0.04404913, 0.00725536])

In [24]:
len(model_XGB.feature_importances_)

14

In [25]:
pd.DataFrame({
    'feature': X_train.columns,
    'importance_RF': model_RF.feature_importances_,
    'importance_XGB': model_XGB.feature_importances_
})

             feature  importance_RF  importance_XGB
0              alpha       0.016473        0.010261
1              delta       0.015548        0.012503
2                  u       0.069593        0.026291
3                  g       0.087337        0.092387
4                  r       0.044086        0.018637
5                  i       0.076715        0.024243
6                  z       0.107297        0.043103
7           redshift       0.508146        0.723142
8             run_ID       0.010917        0.010514
9           rerun_ID       0.000000        0.000000
10           cam_col       0.004124        0.009298
11          field_ID       0.008460        0.009472
12             plate       0.044049        0.020148
13  redshift_upper_3       0.007255        0.000000

In [26]:
pred = model_XGB.predict_proba(X_test)[:, 1]
pd.DataFrame({
    'index': X_test.index,
    'target': pred
}).to_csv('../yemoonsaBigdata/res/003000000.csv', index=False)